Item-Give-Delay: 5
Items:
  - OAK_PLANKS
  - DARK_OAK_LOG
  - DIAMOND
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - DIAMOND_HOE
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - IRON_INGOT
  - IRON_SWORD
  - IRON_AXE
  - IRON_HOE
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - LEATHER
  - LEATHER_CHESTPLATE
  - TRIDENT
  - TURTLE_HELMET
  - WATER_BUCKET
  - LAVA_BUCKET
  - HAY_BLOCK
  - ANVIL
  - BOW
  - CROSSBOW
  - ARROW
  - SPECTRAL_ARROW
  - SNOWBALL
  - EGG
  - ACTIVATOR_RAIL
  - TNT_MINECART
  - PUFFERFISH_BUCKET
  - MILK_BUCKET
  - FISHING_ROD
  - OBSERVER
  - CRAFTING_TABLE
  - ELYTRA
  - FLINT_AND_STEEL
  - HONEY_BLOCK
  - SLIME_BLOCK
  - SAND